layout_spectrum: 0.2851164846215397
typography_spectrum: 0.5558128713164479
color:
  brandStrength: 0.1775250220671296
  lightness: 0.8520669287536293
  saturation: 0.7995351541321725
  rhythmicContrast: 0.7608411526307464
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
name: Strom Social Media
